# Generated by Django 3.1.2 on 2020-11-04 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='imagedb',
            name='i',
        ),
        migrations.RemoveField(
            model_name='imagedb',
            name='j',
        ),
        migrations.AddField(
            model_name='imagedb',
            name='data',
            field=models.CharField(blank='true', max_length=122),
        ),
    ]
