# Generated by Django 3.1.2 on 2020-11-04 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0003_auto_20201104_1416'),
    ]

    operations = [
        migrations.CreateModel(
            name='myImageDataBase',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('LogoLinks', models.CharField(max_length=122)),
            ],
        ),
        migrations.DeleteModel(
            name='imageDB',
        ),
    ]
