# Generated by Django 3.1.2 on 2020-11-04 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0004_auto_20201104_1517'),
    ]

    operations = [
        migrations.CreateModel(
            name='myDataBase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('LogoLinks', models.CharField(max_length=122)),
                ('LogoName', models.CharField(max_length=122)),
            ],
        ),
        migrations.DeleteModel(
            name='myImageDataBase',
        ),
    ]
